--問3
CREATE TABLE categories(
id NUMBER(4) PRIMARY KEY ,
name VARCHAR2(20CHAR) NOT NULL UNIQUE,
registration_date DATE DEFAULT SYSDATE NOT NULL,
update_date DATE DEFAULT SYSDATE NOT NULL
);

CREATE TABLE items(
id NUMBER(4) PRIMARY KEY,
name VARCHAR2(30CHAR) NOT NULL UNIQUE,
price NUMBER(7) DEFAULT 0 NOT NULL,
registration_date DATE DEFAULT SYSDATE NOT NULL ,
update_date DATE DEFAULT SYSDATE NOT NULL,
category_id NUMBER(4),
FOREIGN KEY (category_id) REFERENCES categories(id)
);

--問4
INSERT INTO categories VALUES(1,'菓子類',SYSDATE,SYSDATE);
INSERT INTO categories VALUES(2,'文房具',SYSDATE,SYSDATE);
INSERT INTO categories VALUES(3,'書籍',SYSDATE,SYSDATE);
INSERT INTO categories VALUES(4,'衣類',SYSDATE,SYSDATE);

INSERT INTO items VALUES(1,'システム手帳(A5 サイズ)',8900,SYSDATE,SYSDATE,2);
INSERT INTO items VALUES(2,'キャンディー5 種セット',340,SYSDATE,SYSDATE,1);
INSERT INTO items VALUES(3,'『Java 入門』',2980,SYSDATE,SYSDATE,3);
INSERT INTO items VALUES(4,'カラーペン 3 色セット',340,SYSDATE,SYSDATE,2);
INSERT INTO items VALUES(5,'『Java 入門』（第 2 版)',2980,SYSDATE,SYSDATE,3);

COMMIT;

DROP TABLE items;
DROP TABLE categories;
